import LegalPageLayout from "@/components/LegalPageLayout";

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout title="Terms of Service">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use
        of the AgreeWise.ai website and services (&quot;Service&quot;). By
        accessing or using the Service, you agree to be bound by these Terms.
      </p>

      <h2>1. Use of the Service</h2>
      <p>
        AgreeWise.ai provides an AI-powered analysis of legal documents. You may
        use the service by providing a URL, pasting text, or uploading a
        document. You agree not to use the Service for any unlawful purpose.
      </p>

      <h2>2. Disclaimer of Warranty</h2>
      <p>
        The analysis provided by AgreeWise.ai is for **informational purposes
        only** and is generated by an automated AI system. It does not
        constitute legal advice. We make no warranty or representation about the
        accuracy, reliability, or completeness of the analysis. You should not
        rely on this information as a substitute for, nor does it replace,
        professional legal advice. Always consult a qualified legal professional
        for advice on your specific situation.
      </p>

      <h2>3. Content You Provide</h2>
      <p>
        You retain ownership of any content you submit for analysis. By using
        the service, you grant us a temporary, non-exclusive, worldwide,
        royalty-free license to use, process, and transmit your content solely
        for the purpose of providing the analysis service to you. This license
        terminates automatically once the analysis is complete. We do not store
        your documents, text, or URLs after processing.
      </p>

      <h2>4. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by applicable law, AgreeWise.ai shall
        not be liable for any indirect, incidental, special, consequential, or
        punitive damages, or any loss of profits or revenues, whether incurred
        directly or indirectly, or any loss of data, use, goodwill, or other
        intangible losses, resulting from (a) your access to or use of or
        inability to access or use the Service; (b) any analysis provided by the
        Service.
      </p>

      <h2>5. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. We will notify
        you of any changes by posting the new Terms on this page. Your continued
        use of the Service after any such change constitutes your acceptance of
        the new Terms.
      </p>
    </LegalPageLayout>
  );
}
